const gamesMock = [
  {
    id: null,
    family_id: 1,
    brand_id: 1,
    name: 'Sequence',
    description: `Play a card from your hand, and place a chip on a corresponding space on the game board. When you have five in a row, it's a SEQUENCE. Block your opponents or remove their chips. The first player or team with the required number of SEQUENCES wins!`,
    age_recommended: 7,
    play_time: 30,
    min_players: 2,
    max_players: 12,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  },
  {
    id: null,
    family_id: 2,
    brand_id: 9,
    name: 'UNO',
    description: 'El juego clásico de cartas de hacer coincidir números y colores. PARA TODA LA FAMILIA - Los jugadores compiten en turnos haciendo coincidir las cartas que tienen en la mano con el color o el número de la carta que aparece en la parte superior de la baraja.',
    age_recommended: 7,
    play_time: 10,
    min_players: 2,
    max_players: 10,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  },
  {
    id: null,
    family_id: 3,
    brand_id: 2,
    name: 'Dixit',
    description: 'Dixit is the lovingly illustrated game of creative guesswork, where your imagination unlocks the tale. In this award-winning board game, players will use the beautiful imagery on their cards to bluff their opponents and guess which image matches the story.',
    age_recommended: 8,
    play_time: 30,
    min_players: 3,
    max_players: 6,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  },
  {
    id: null,
    family_id: 4,
    brand_id: 2,
    name: 'Splendor',
    description: 'Splendor es un juego de recolección de fichas y desarrollo de cartas. Los jugadores son comerciantes del Renacimiento que intentan comprar minas de gemas, medios de transporte y tiendas, con el fin de adquirir la mayor cantidad de puntos de prestigio.',
    age_recommended: 10,
    play_time: 40,
    min_players: 2,
    max_players: 4,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  },
  {
    id: null,
    family_id: 5,
    brand_id: 6,
    name: 'Mapominoes',
    description: `It's like dominoes but with maps, as you build a map of Europe, by connecting countries that share a common border. Stay one step ahead of your opponents, as you race to be the first player to play all your country cards on the table and win this geography game.`,
    age_recommended: 8,
    play_time: 30,
    min_players: 2,
    max_players: 5,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  },
  {
    id: null,
    family_id: 6,
    brand_id: 5,
    name: 'Catan',
    description: `Settlers of Catan is a strategy board game involving smart resource management. Your goal in Settlers of Catan is to reach ten victory points. You earn victory points from building settlements, cities, and development cards; having the longest road and the largest army.`,
    age_recommended: 10,
    play_time: 60,
    min_players: 2,
    max_players: 4,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  },
  {
    id: null,
    family_id: 12,
    brand_id: 9,
    name: 'Phase 10',
    description: `JUEGO en el que ganas cuando completas las diez fases, que varían entre dos conjuntos de tres, una corrida de siete o siete cartas del mismo color. SORPRESA con los objetivos cambiantes de cada fase. Los jugadores deben completar la etapa antes de avanzar a la siguiente ronda.`,
    age_recommended: 7,
    play_time: 60,
    min_players: 2,
    max_players: 6,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  },
  {
    id: null,
    family_id: 2,
    brand_id: 9,
    name: 'DOS',
    description: 'Like UNO, the object of DOS Second Edition is to be the first player to get rid of all your cards, but now there are two discard piles and players are allowed to add two cards together to help empty their hand faster.',
    age_recommended: 7,
    play_time: 10,
    min_players: 2,
    max_players: 4,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  },
  {
    id: null,
    family_id: 2,
    brand_id: 9,
    name: 'UNO dare',
    description: 'The familiar fun race to yell “UNO!” comes with wild, new choices! While playing the color and numbers matching game, you’re faced with a decision: draw extra cards or take a dare! Dare cards come in 3 categories: Family, Show-Off and Daredevil',
    age_recommended: 7,
    play_time: 10,
    min_players: 2,
    max_players: 10,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  },
  {
    id: null,
    family_id: 1,
    brand_id: 2,
    name: 'Sequence for kids',
    description: 'Juega una carta de animal de tu mano, coloca una ficha en el tablero… cuando consigas 4 en fila, ¡es SEQUENCE',
    age_recommended: 3,
    play_time: 10,
    min_players: 2,
    max_players: 4,
    rating: 0.0,
    rating_voters: 0,
    deleted: false
  }
];

module.exports = {
  gamesMock
}